### ISSUE TITLE
Add back support for --source-dir flag?

### ISSUE THREAD

**Issue by bigsmoke** [bigsmoke/.bigsmoke#1]
Because I didn't anticipate that @quinox would like to use some of my changes, I removed support for an option (`--source-dir`) that I didn't need for my use case.

Would you like this option back, @quinox?

**Comment by quinox** [comment]
Did you remove it though? https://github.com/bigsmoke/.bigsmoke/blob/master/conf-sync#L351 seems fine, using `username` if possible with fallback to `example-conf` and the option to override it.

**Comment by bigsmoke** [comment]
Hmm. Maybe I just removed the `__home__` needle support and the
`--source-dir` support, after all. :/

**Comment by quinox** [comment]
Dropping support for `__home__` is no problem, ATM I only have `quinox` as username on system that work on.
